options(stringsAsFactors = FALSE)

suppressPackageStartupMessages({
  library(data.table)
})

root <- Sys.getenv("GO_2KB_DIR")
if (!nzchar(root)) stop("Set GO_2KB_DIR to the directory generated by build_four_TE_class_2kb_gene_lists.R.")
list_dir <- file.path(root, "gene_lists")
annotation_file <- file.path(root, "annotation", "all.GOSlim_assignment")
result_dir <- file.path(root, "GO_results")
dir.create(result_dir, recursive = TRUE, showWarnings = FALSE)

class_files <- c(
  "Shared-TE" = "Shared_TE_gene_ids_2kb.txt",
  "Low-Fst TE" = "Low_Fst_TE_gene_ids_2kb.txt",
  "Mid-Fst TE" = "Mid_Fst_TE_gene_ids_2kb.txt",
  "High-Fst TE" = "High_Fst_TE_gene_ids_2kb.txt"
)

go <- fread(annotation_file, header = FALSE, sep = "\t", quote = "")
setnames(go, c("Model_ID", "GO_ID", "Ontology", "GO_Term", "Evidence", "Source"))
go[, Gene_ID := sub("\\.[0-9]+$", "", Model_ID)]
go <- unique(go[, .(Gene_ID, GO_ID, Ontology, GO_Term)])
go <- go[Ontology %in% c("P", "F", "C")]

background <- unique(readLines(file.path(list_dir,
  "background_all_four_class_TE_nearby_gene_ids.txt")))
background <- intersect(background, unique(go$Gene_ID))
N_bg <- length(background)
bg_term <- go[Gene_ID %in% background, .(Background_Count = uniqueN(Gene_ID)),
              by = .(GO_ID, Ontology, GO_Term)]

all_results <- list()
coverage <- list()
for (cls in names(class_files)) {
  raw_query <- unique(readLines(file.path(list_dir, class_files[[cls]])))
  query <- intersect(raw_query, background)
  n_query <- length(query)
  q_term <- go[Gene_ID %in% query, .(Gene_Count = uniqueN(Gene_ID)),
               by = .(GO_ID, Ontology, GO_Term)]
  res <- merge(q_term, bg_term, by = c("GO_ID", "Ontology", "GO_Term"), all.x = TRUE)
  res[, `:=`(
    TE_Class = cls,
    Query_Annotated_Genes = n_query,
    Background_Annotated_Genes = N_bg,
    Gene_Ratio = Gene_Count / n_query,
    Background_Ratio = Background_Count / N_bg
  )]
  res[, Fold_Enrichment := Gene_Ratio / Background_Ratio]
  res[, P_value := phyper(Gene_Count - 1L, Background_Count,
                           N_bg - Background_Count, n_query, lower.tail = FALSE)]
  res[, FDR := p.adjust(P_value, method = "BH")]
  setorder(res, FDR, -Fold_Enrichment, -Gene_Count)
  all_results[[cls]] <- res
  coverage[[cls]] <- data.table(
    TE_Class = cls,
    Input_genes = length(raw_query),
    Annotated_in_GOSlim = n_query,
    Annotation_coverage = n_query / length(raw_query)
  )
}

result <- rbindlist(all_results, use.names = TRUE, fill = TRUE)
result[, Ontology_Name := fifelse(Ontology == "P", "Biological process",
  fifelse(Ontology == "F", "Molecular function", "Cellular component"))]
sig <- result[Gene_Count >= 5 & FDR < 0.05 & Fold_Enrichment > 1]

fwrite(result, file.path(result_dir, "four_TE_class_GOSlim_enrichment_all.csv"), bom = TRUE)
fwrite(sig, file.path(result_dir, "four_TE_class_GOSlim_enrichment_significant.csv"), bom = TRUE)
fwrite(rbindlist(coverage), file.path(result_dir, "GOSlim_annotation_coverage.csv"), bom = TRUE)

# A compact plotting table: top three BP terms per class, then retain the union
# so the four classes remain directly comparable.
top_bp <- sig[Ontology == "P", head(.SD, 3), by = TE_Class]
selected_terms <- unique(top_bp[, .(GO_ID, GO_Term, Ontology, Ontology_Name)])
plot_dt <- merge(
  result[Ontology == "P"], selected_terms,
  by = c("GO_ID", "GO_Term", "Ontology", "Ontology_Name")
)
plot_dt[, Significant := FDR < 0.05 & Fold_Enrichment > 1]
fwrite(plot_dt, file.path(result_dir, "GOSlim_BP_selected_terms_for_plot.csv"), bom = TRUE)

# Union of all significant GO-Slim terms across BP/MF/CC, evaluated in every
# TE class. This table is used for the compact cross-class dot plot.
sig_union <- unique(sig[, .(GO_ID, GO_Term, Ontology, Ontology_Name)])
plot_union <- merge(
  result, sig_union,
  by = c("GO_ID", "GO_Term", "Ontology", "Ontology_Name")
)
plot_union[, Significant := Gene_Count >= 5 & FDR < 0.05 & Fold_Enrichment > 1]
fwrite(plot_union,
       file.path(result_dir, "GOSlim_significant_term_union_for_plot.csv"), bom = TRUE)

writeLines(c(
  "GO-Slim enrichment for genes within 2 kb of four MSU-reference TE classes.",
  "Annotation: official Rice Genome Annotation Project release 7 all.GOSlim_assignment.",
  "Background: all annotated genes within 2 kb of any of the four analyzed TE classes.",
  "Test: upper-tail hypergeometric test; Benjamini-Hochberg FDR within each TE class.",
  "Significant table filter: Gene_Count >= 5, FDR < 0.05, Fold_Enrichment > 1.",
  "The TE-nearby background is used to reduce genomic-context bias."
), file.path(result_dir, "README_GOSlim_enrichment.txt"))

print(rbindlist(coverage))
print(sig[, .N, by = .(TE_Class, Ontology_Name)])
message("Saved GO-Slim enrichment results to: ", result_dir)
